# Generated by Django 5.2.7 on 2025-11-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='blogs/'),
        ),
    ]
